---
title: "Chi sono"
date: 2025-07-22
createdDate: 2023-06-12T12:00:00+02:00
layout: cv_comune
language: it
ShowToc: true
showbio: true
---

== Più informazioni

=== Di cosa mi occupo
Dal 2023 lavoro come *sistemista informatico*, mantenendo gli apparati di rete degli enti di ricerca per cui ho lavorato e gestendone account e permessi degli utenti connessi. +
Per via delle posizioni che ho ricoperto ho dovuto in più occasioni ricoprire il ruolo del *programmatore*, quello del *webmaster*, quello del *data manager/curator*, quello dell'**assistente tecnico** occupandomi di piccole riparazioni e in alcuni casi quello dell'**assistente alla regia** - gestendo audio, presentazioni e registrazioni di meeting internazionali.

Dal 2023 a oggi ho lavorato:

  * Per conto di mailto:damiano@verzulli.it[_Soabit s.r.l._, title="Datore di lavoro: Damiano Verzulli"] presso *ICRANet Pescara* (01/2023 - 06/2023);
  * Per l'**mailto:segreteria@spin.cnr.it[Istituto CNR-SPIN, title="Segreteria CNR-SPIN"]** - località Monte S. Angelo, Napoli (07/2024 - 12/2025, _in corso_).

=== Le mie competenze
Oltre alla mia preparazione accademica da *Dottore in Ingegneria Meccanica Triennale* - cui devo le mie abilità organizzative/gestionali e le mie capacità di progettare macchine semplici, dimensionare o scegliere da catalogo componenti e di selezionare/dimensionare un'unità di condizionamento dell'aria sia a uso domestico sia a uso industriale - ho un ampio set di competenze anche nell'ambito dell'**informatica**. Ho familiarità con le *interfacce a riga di comando*, in particolare con i terminali dei sistemi operativi Unix/Linux, so programmare in *Python*, Matlab e altri linguaggi, so realizzare *siti web da zero* partendo dal server HTTP fino al frontend, so gestire *ipervisori* con molteplici servizi esposti a internet, so realizzare *siti/e-book documentali* con vari linguaggi di markup (pref. Asciidoc) e tanto altro.

Ma al di sopra di ogni altra cosa #so usare bene il pacchetto Office#.

=== La mia formazione
Diplomato al Liceo Scientifico Margherita Hack di Baronissi ho poi conseguito la *Laurea Triennale in Ingegneria Meccanica* presso l'Università di Salerno, alternando gli studi con esperienze lavorative e di formazione trasversale - anche all'estero. Durante gli studi ho collaborato con un team di colleghi nella riapertura informale del *Linux User Group* dell'università, specializzandomi nel contempo anche in ciò che riguarda il mondo dei sistemi Linux e dell'informatica in generale. Terminato il CdL ho poi completato un Corso di Perfezionamento - *Master in Data Management and Curation* - presso la SISSA (Trieste), integrando conoscenze di programmazione in Python per gestione e parsing di dati scientifici.

// Attualmente sono studente Magistrale di Informatica presso l'Università degli Studi di Salerno. 

=== Le mie capacità
Mi ritengo una persona con spiccate *capacità organizzative*, in grado di gestire in autonomia le proprie mansioni ma capace di adattarsi con *flessibilità* alle esigenze del team. Collaborando con enti di ricerca ho maturato esperienza nel lavorare in *contesti multiculturali*, adottando una comunicazione diretta ed efficace con i colleghi ricercatori indipendentemente dalla lingua parlata.

Ho un *approccio paziente* che mantengo anche in situazioni complesse o sotto pressione, trovando soluzioni equilibrate senza perdere di vista il rispetto e la professionalità. Credo molto nel valore del lavoro di squadra e mi impegno sempre nel *mantenere rapporti positivi* con i colleghi. #Occasionalmente offro anche il caffè#.

=== I miei hobby
Per la sorpresa di nessuno, spendo gran parte del mio tempo libero sui computer; in particolare ho un *piccolo homelab* che include un virtualizzatore realizzato con componenti "di fortuna" il quale espone una serie di servizi tra cui un _Nextcloud_, una VPN _WireGuard_ e un _Navidrome_. Oltre a questo sono appassionato di *videogiochi* e provo particolare affetto nei confronti delle saghe di _Dark Souls_, _Monster Hunter_ e _Metal Gear_.

Sono inoltre volontario giovane di *Croce Rossa Italiana* presso il _Comitato di Benevento_, dove occasionalmente partecipo ad attvità in piazza od organizzative.

// == Dettagli
// === Percorso di studi
//   * _2012-2017_: *Diploma di Istruzione Superiore* conseguito presso il Liceo Scientifico Margherita Hack, Baronissi (ex IIS Baronissi) - voto di maturità 96/100.
//   * _2017-2024_: *Laurea Triennale in Ingegneria Meccanica* presso l'Università degli Studi di Salerno - voto finale 97/110.
//   * _2024-2025_: *Master in Data Management and Curation* presso la Scuola Internazionale Superiore di Studi Avanzati (SISSA), Trieste.

// === Elaborati di tesi
//   * Maturità: "link:/tesina_maturità.pdf[*The Dark Side of The Moon: la faccia oscura della vita umana*^]".
//   * Triennale: "*Simulazione di un generatore eolico off-grid*" (link non disponibile).
//   * MDMC: "link:https://doi.org/10.5281/zenodo.15700974[*AMORE: a GUI to promote migration from paper to eLN*^]".
// //Sezione per i lavori di tesi? Meglio se con PDF?

=== Certificazioni
[cols="3,3,2,1"]
|===
| Nome percorso | Ambito | Codice | Download

| *Cambridge English First, Level B2* | Lingua inglese | 0053909676 | link:/documenti/università/FCE_cambridge_first_B1.pdf[Link^]
| *Forcepoint NGFW Administrator* | Sistemi informatici | 014242/2025 | link:/documenti/CNR/Forcepoint_NGFW_Administrator_7793204_23218.pdf[Link^]
| *Master in Data Management and Curation* | Data management | -- | link:/documenti/CNR/MDMC_ITA.pdf[Link^]
| *Digital Manufacturing - Prototipazione 3D e CNC* | Progettazione meccanica | Formatemp 094 PROT D211 1983 | link:/documenti/università/Attestato_Digital_Manufacturing_Wintime_P21WT036.pdf[Link^]
|===

==== Altri attestati
[cols="3,3,2,1"]
|===
| Nome percorso | Ambito | Codice | Download

| Tavolo Tecnico ICT | Sistemi informatici | -- | link:/documenti/CNR/tavolo_tecnico_ICT_Chieti.pdf[Link^]
| Salute e sicurezza nei luoghi di lavoro - Formazione specifica Rischio basso | Sicurezza | Jn6Da4nmfM | link:/documenti/CNR/Attestato_rischio_basso.pdf[Link^]
| Formazione Generale +
per i Lavoratori | Sicurezza | 137413_5/15footnote:[Verifica l'autenticità del certificato su link:https://opnitalialavoro.it/verifica-dellautenticita/[opnitalialavoro.it, window=_blank]; i campi "nome" e "cognome" sono caps-insensitive (es. D'AMICO = d'amico) ma l'apostrofo è necessario.] | link:/documenti/università/Sicurezza_sul_Lavoro_P21WT036.pdf[Link^]
| Estate INPSieme 2017 | Lingua inglese, estero | N/A  | link:/documenti/università/Estate_INPSieme_2017.jpg[Link^]
| Corso di Formazione +
per Volontari CRI | Croce Rossa | CAM/2024/CRI/8427/5 | link:/documenti/corso-di-formazione-per-volontari.pdf[Link^]
| Percorso Gioventù | Croce Rossa | CAM/2025/PG/5058/4 | link:/documenti/percorso-gioventù.pdf[Link^]
|===


// * "*DIGITAL MANUFACTURING - Prototipazione 3D e CNC*" (giugno 2021 - agosto 2021) - cod. prog. Formatemp "094 PROT D211 1983". link:/documenti/università/Attestato_Digital_Manufacturing_Wintime_P21WT036.pdf[Attestato di frequenza., window=_blank]
// * "*Corso di Formazione Generale per i Lavoratori*" (luglio 2021) - cod. att. (link:https://opnitalialavoro.it/verifica-dellautenticita/[137413_5/15, title="Verifica autenticità", window=_blank]). link:/documenti/università/Sicurezza_sul_Lavoro_P21WT036.pdf[Attestato di superamento., window=_blank]
// * Esperienza di studio all'estero *Estate INPSieme 2017* in Greenwich, Londra, della durata di quattro settimane compresa di corso intensivo di lingua inglese (11/07/2017 - 08/08/2017). link:/documenti/università/Estate_INPSieme_2017.jpg[Attestato di partecipazione., window=_blank]
// * *_Cambridge English First_, Level B2* (luglio 2016) - cert. num. 0053909676. +
// Esame di verifica conseguito in data 22/07/2016 e superato con voto finale di *174 - Grade B*. link:/documenti/università/FCE_cambridge_first_B1.pdf[Vedi certificato.^]

=== Progetti minori
  * Assemblaggio, setup e manutenzione di un piccolo homelab, attualmente comprendente un server domestico con Proxmox VE per self-hosting di servizi open source (Navidrome, Nextcloud...), e un NAS ODROID-HC4 per backup (2025 - _in corso_).
  * Realizzazione e mantenimento di questo link:/[sito personale], usando Hugo come CMS, la soluzione di hosting Oracle Cloud Infrastructure Free-Tier come server fisico, Almalinux 9 come S.O. e Apache HTTP Server come webserver (2023 - _in corso_).
  * Realizzazione di un sito web per il progetto link:https://foxes.spin.cnr.it/[FOXES^] del CNR-SPIN, utilizzando una versione custom del tema Hugo-Hero (novembre 2024).
  * Progettazione trasmissione, assi/alberi e supporti di una ipotetica pressa meccanica a doppio eccentrico per l'esame di Costruzione di Macchine (giugno - agosto 2022).
  * Collaborazione nelle operazioni tecniche della perizia balistica per la Proc. Pen. 2144/2018 mod.21 (maggio 2018 - link:/documenti/università/collaborazione_perizia.pdf[dichiarazione di collaborazione^]).

// == Capacità e competenze tecniche
// === Da ingegnere e progettista meccanico
// > link:/cv/ingegnere#hardskill[Ulteriori informazioni]

// * *Conoscenze accademiche di ingegneria meccanica*: preparazione accademica da ingegnere meccanico triennale; progettazione di impianti di condizionamento, scelta da catalogo di componenti idraulici/aeraulici.
// * *Disegno tecnico e CAD*: capacità di lettura dei disegni ISO; esperienza con AutoCAD, NanoCAD, Catia V5, Solidworks e FreeCAD; conoscenza di base di Ansys.

// === Da informatico
// > link:/cv/informatico#hardskill[Ulteriori informazioni]

// * *Sistemi operativi*: Linux, Windows (XP – 11); esperienza con MacOS e Android; capacità di ripristino OS danneggiato; esperienza con interfacce a riga di comando.
// * *Sviluppo web*: fondamenti di programmazione web front-end; CMS/framework vari (Hugo, Wordpress, Django, Flask...).
// * *Manutenzione di rete*: manutenzione di PC da ufficio e server; backup e versioning, monitoraggio risorse di rete, accesso remoto alle macchine; virtualizzazione, containerizzazione e automazione.
// * *Programmazione*: Python, LabVIEW, Matlab/Simulink, Bash; fondamenti di GNU Octave, C e altri linguaggi, gestione database SQL; esperienza con git.
// * *Office*: competenza nelle suite da ufficio più diffuse - MS Office 365, LibreOffice, Google Docs; automazione con libreria Python "docx"; linguaggi di markup LaTeX, Asciidoctor, Markdown, reStructuredText; esperienza di gestione di repository documentali (Hugo, Antora, Obsidian).
// * *Self-hosting*: gestione server Apache HTTP e certificati SSL; installazione e gestione di applicativi server sia in bare metal sia via Docker (es. Nextcloud, Snipeit...).

=== Capacità e competenze trasversali
{{< skill skill=altre >}}

=== Capacità e competenze organizzative/relazionali (soft skill)
{{< skill skill=soft >}}

== Download
link:/curriculum/SYS.pdf[Scarica la versione PDF.^] +
link:/curriculum/europass.pdf[Scarica il curriculum in formato Europass.^]

== Altre pagine
// * link:/cv/damico[Chi sono]
* link:/cv/esperienze[Esperienze lavorative e formative]
* link:/cv/competenze[Competenze tecniche]
* link:/curriculum/europass.pdf[Europass (PDF)^]


// [cols=3]
// |===
// |Precisione:
// |
// |★★★★★
//
// |Problem solving:
// |
// |★★★★★
//
// |Pazienza:
// |
// |★★★★☆
//
// |Pianificazione:
// |
// |★★★★☆
//
// |Rapporti interpersonali:
// |
// |★★★★☆
//
// |Lavoro di squadra:
// |
// |★★★★☆
//
// |Saper ascoltare:
// |
// |★★★☆☆
//
// |Autonomia:
// |
// |★★☆☆☆
// |===
