---
title: "Chi sono"
date: 2025-03-15
createdDate: 2023-06-12T12:00:00+02:00
layout: cv_comune
language: it
ShowToc: true
showbio: true
---

== Più informazioni

=== Di cosa mi occupo
Dal 2023 lavoro come sistemista informatico, mantenendo gli apparati di rete degli enti di ricerca per cui ho lavorato e gestendone account e permessi degli utenti connessi. +
Per via delle posizioni che ho ricoperto ho dovuto in più occasioni ricoprire il ruolo del programmatore, quello del webmaster, quello del data manager/curator, quello dell'assistente tecnico occupandomi di piccole riparazioni e in alcuni casi quello dell'assistente alla regia - gestendo audio, presentazioni e registrazioni di meeting internazionali.

Dal 2023 a oggi ho lavorato:

  * Per conto di mailto:damiano@verzulli.it[Soabit s.r.l., title="Datore di lavoro: Damiano Verzulli"] presso #ICRANet Pescara# (01/2023 - 06/2023);
  * Per l'#mailto:segreteria@spin.cnr.it[Istituto CNR-SPIN, title="Segreteria CNR-SPIN"]# - località Monte S. Angelo, Napoli (07/2024 - 12/2025, _in corso_).

=== Le mie competenze
Diplomato al Liceo Scientifico Margherita Hack di Baronissi ho poi conseguito la Laurea Triennale in Ingegneria Meccanica presso l'Università di Salerno, alternando gli studi con esperienze lavorative e di formazione trasversale - anche all'estero. Durante gli studi ho collaborato con un team di colleghi nella riapertura informale del Linux User Group dell'università, specializzandomi nel contempo anche in ciò che riguarda il mondo dei sistemi Linux e dell'informatica in generale. Terminato il CdL ho poi completato un Corso di Perfezionamento in data management presso il SISSA (Trieste) in cui ho integrato conoscenze di programmazione in Python per gestione e parsing di dati scientifici.

// Attualmente sono studente Magistrale di Informatica presso l'Università degli Studi di Salerno. 

=== I miei hobby
Per la sorpresa di nessuno, spendo gran parte del mio tempo libero sui computer; in particolare ho un piccolo homelab che include un virtualizzatore realizzato con componenti "di fortuna" il quale espone una serie di servizi tra cui un Nextcloud, una VPN WireGuard e un Navidrome. Oltre a questo sono appassionato di videogiochi con particolare affetto nei confronti delle saghe di Dark Souls e Metal Gear.

Occasionalmente faccio anche volontariato, e sono volontario di Croce Rossa Italiana presso il Comitato di Benevento.

== Dettagli
=== Percorso di studi
  * _2012-2017_: *Diploma di Istruzione Superiore* conseguito presso il Liceo Scientifico Margherita Hack, Baronissi (ex IIS Baronissi) - voto di maturità 96/100. +
  Tesi di maturità (vecchio ordinamento): "The Dark Side of The Moon: la faccia oscura della vita umana".
  * _2017-2024_: *Laurea Triennale in Ingegneria Meccanica* presso l'Università degli Studi di Salerno - voto finale 97/110. +
  Tesi di laurea: "Simulazione di un generatore eolico off-grid".
  * _2024-2025_: *Master in Data Management and Curation* presso la Scuola Internazionale Superiore di Studi Avanzati (SISSA), Trieste. +

=== Elaborati di tesi
  * Maturità: "*The Dark Side of The Moon: la faccia oscura della vita umana*" (link non disponibile)
  * Triennale: "*Simulazione di un generatore eolico off-grid*" (link non disponibile)
  * MDMC: "link:https://doi.org/10.5281/zenodo.15700974[*AMORE: a GUI to promote migration from paper to eLN*^]".
//Sezione per i lavori di tesi? Meglio se con PDF?

=== Attestati e certificazioni
  * "*DIGITAL MANUFACTURING - Prototipazione 3D e CNC*" (giugno 2021 - agosto 2021) - cod. prog. Formatemp "094 PROT D211 1983". link:/certifications/Attestato_Digital_Manufacturing_Wintime_P21WT036.pdf[Attestato di frequenza., window=_blank]
  * "*Corso di Formazione Generale per i Lavoratori*" (luglio 2021) - cod. att. (link:https://opnitalialavoro.it/verifica-dellautenticita/[137413_5/15, title="Verifica autenticità", window=_blank]). link:/certifications/Sicurezza_sul_Lavoro_P21WT036.pdf[Attestato di superamento., window=_blank]
  * Esperienza di studio all'estero *Estate INPSieme 2017* in Greenwich, Londra, della durata di quattro settimane compresa di corso intensivo di lingua inglese (11/07/2017 - 08/08/2017). link:/certifications/Estate_INPSieme_2017.jpg[Attestato di partecipazione., window=_blank]
  * Certificazione *_Cambridge English First_, Level B2* (luglio 2016) - cert. num. 0053909676. +
  Esame di verifica conseguito in data 22/07/2016 e superato con voto finale di *174 - Grade B*.

=== Progetti minori
  * Assemblaggio, setup e manutenzione di un piccolo server domestico con Proxmox VE per automazione routine di backup e self-hosting di servizi open source (Homebox, Nextcloud...).
  * Realizzazione di un sito web per il progetto link:https://foxes.spin.cnr.it/[FOXES^] del CNR-SPIN, riutilizzando tema e contenuti del prototipo scartato per il nuovo sito ICRANet.
  * Realizzazione e mantenimento di questo link:/[sito personale], usando Hugo come CMS, la soluzione di hosting Oracle Cloud Infrastructure Free-Tier come server fisico, Almalinux 9 come S.O. e Apache HTTP Server come webserver.
  * Realizzazione prototipo di un nuovo sito per link:https://it.wikipedia.org/wiki/ICRANet[ICRANet^] con CMS Hugo (_cancellato_).
  * Progettazione trasmissione, assi/alberi e supporti di una ipotetica pressa meccanica a doppio eccentrico per l'esame di Costruzione di Macchine (giugno - agosto 2022).

== Capacità e competenze tecniche
=== Da ingegnere e progettista meccanico
> link:/cv/ingegnere#hardskill[Ulteriori informazioni]

* *Conoscenze accademiche di ingegneria meccanica*: preparazione accademica da ingegnere meccanico triennale; progettazione di impianti di condizionamento, scelta da catalogo di componenti idraulici/aeraulici.
* *Disegno tecnico e CAD*: capacità di lettura dei disegni ISO; esperienza con AutoCAD, NanoCAD, Catia V5, Solidworks e FreeCAD; conoscenza di base di Ansys.

=== Da informatico
> link:/cv/informatico#hardskill[Ulteriori informazioni]

* *Sistemi operativi*: Linux, Windows (XP – 11); esperienza con MacOS e Android; capacità di ripristino OS danneggiato; esperienza con interfacce a riga di comando.
* *Sviluppo web*: fondamenti di programmazione web front-end; CMS/framework vari (Hugo, Wordpress, Django, Flask...).
* *Manutenzione di rete*: manutenzione di PC da ufficio e server; backup e versioning, monitoraggio risorse di rete, accesso remoto alle macchine; virtualizzazione, containerizzazione e automazione.
* *Programmazione*: Python, LabVIEW, Matlab/Simulink, Bash; fondamenti di GNU Octave, C e altri linguaggi, gestione database SQL; esperienza con git.
* *Office*: competenza nelle suite da ufficio più diffuse - MS Office 365, LibreOffice, Google Docs; automazione con libreria Python "docx"; linguaggi di markup LaTeX, Asciidoctor, Markdown, reStructuredText; esperienza di gestione di repository documentali (Hugo, Antora, Obsidian).
* *Self-hosting*: gestione server Apache HTTP e certificati SSL; installazione e gestione di applicativi server sia in bare metal sia via Docker (es. Nextcloud, Snipeit...).

=== Altre capacità e competenze
{{< skill skill=altre >}}

=== Capacità e competenze organizzative/relazionali (soft skill)
{{< skill skill=soft >}}

== Download
link:/curriculum/comune.pdf[Scarica la versione PDF.^] +
link:/curriculum/europass.pdf[Scarica il curriculum in formato Europass.^]

=== Allegati
. link:/certifications/FCE_cambridge_first_B1.pdf[Certificato FCE liv. B2^]
. link:/certifications/Attestato_Digital_Manufacturing_Wintime_P21WT036.pdf[Attestato corso di formazione generale per i lavoratori (OPN Italia)^]
. link:/certifications/Sicurezza_sul_Lavoro_P21WT036.pdf[Attestato corso "DIGITAL MANUFACTURING" (EDESIA/WINTIME)^]

link:/curriculum/comune_allegati.pdf[Scarica CV e allegati (PDF unico).^] +
link:/certifications/allegati_cv.pdf[Scarica solo gli allegati.^]

// [cols=3]
// |===
// |Precisione:
// |
// |★★★★★
//
// |Problem solving:
// |
// |★★★★★
//
// |Pazienza:
// |
// |★★★★☆
//
// |Pianificazione:
// |
// |★★★★☆
//
// |Rapporti interpersonali:
// |
// |★★★★☆
//
// |Lavoro di squadra:
// |
// |★★★★☆
//
// |Saper ascoltare:
// |
// |★★★☆☆
//
// |Autonomia:
// |
// |★★☆☆☆
// |===
