---
title: "CV comune"
date: 2025-02-27
createdDate: 2023-06-12T12:00:00+02:00
url: "/cv/comune"
layout: cv_comune
language: it

---

== Esperienze lavorative
  * *link:/cv/informatico/++#cnr-spin++[Sistemista informatico, title=Dettagli]* per l'#Istituto CNR-SPIN# - località Monte S. Angelo, Napoli (01/07/2024 - 30/06/2025, _in corso_). +
  Ruoli: manutenzione di rete, gestione server, sviluppo software open-source, gestione di cloud storage ed eLN link:https://en.wikipedia.org/wiki/Electronic_lab_notebook[^?^^, title="Wikipedia: Electronic lab notebook"], data curation, assistenza tecnica.
  * *link:/cv/informatico/++#icranet++[++Sistemista informatico++, title=Dettagli]* per conto di mailto:damiano@verzulli.it[Soabit s.r.l., title="Datore di lavoro: Damiano Verzulli"] - via Unità d'Italia, 224, Chieti - presso #ICRANet Pescara# (09/01/2023 - 30/06/2023). +
  Ruoli: consulenza informatica, gestione server e portali web, organizzazione tecnica di meeting e convegni in presenza e online, assistenza tecnica, piccole riparazioni.

=== Esperienze minori
  * Webmaster per l'A.S.D. https://web.archive.org/web/20240513011758/https://iasa-italia.org/[IASA Italia^, title="iasa-italia.it su Internet Archive"] (_sine data_, 2016 - 2021). Gestione e manutenzione di un sito web con CMS Wordpress.

=== Progetti minori
  * Assemblaggio, setup e manutenzione di un piccolo server domestico con Proxmox VE per automazione routine di backup e self-hosting di servizi open source (Homebox, Nextcloud...).
  * Realizzazione di un sito web per il progetto link:https://foxes.spin.cnr.it/[FOXES^] del CNR-SPIN, riutilizzando tema e contenuti del prototipo scartato per il nuovo sito ICRANet.
  * Realizzazione e mantenimento di questo link:/[sito personale], usando Hugo come CMS, la soluzione di hosting Oracle Cloud Infrastructure Free-Tier come server fisico, Almalinux 9 come S.O. e Apache HTTP Server come webserver.
  * Realizzazione prototipo di un nuovo sito per link:https://it.wikipedia.org/wiki/ICRANet[ICRANet^] con CMS Hugo (_cancellato_).
  * Progettazione trasmissione, assi/alberi e supporti di una ipotetica pressa meccanica a doppio eccentrico per l'esame di Costruzione di Macchine (giugno - agosto 2022).

== Istruzione
  * _Master in Data Management and Curation_ presso la Scuola Internazionale Superiore di Studi Avanzati (SISSA), Trieste (14/09/2024 - 31/05/2025, _in corso_). +
  Tesi conclusiva: _da concordare con il relatore_.
  * Laurea Triennale in Ingegneria Meccanica presso l'Università degli Studi di Salerno - voto finale 97/110 (2017 - 2024). +
  Tesi di laurea: "Simulazione di un generatore eolico off-grid".
  * Diploma di Istruzione Superiore conseguito presso il Liceo Scientifico Margherita Hack, Baronissi SA (ex IIS Baronissi) - voto di maturità 96/100 (2012 - 2017). +
  Tesi di maturità (vecchio ordinamento): "The Dark Side of The Moon: la faccia oscura della vita umana".
//Sezione per i lavori di tesi? Meglio se con PDF?

=== Lingue
  * Italiano - madrelingua
  * Inglese - livello Cambridge First B2

=== Corsi di formazione (attestati)
  * "*DIGITAL MANUFACTURING - Prototipazione 3D e CNC*" (giugno 2021 - agosto 2021) - cod. prog. Formatemp "094 PROT D211 1983". link:/certifications/Attestato_Digital_Manufacturing_Wintime_P21WT036.pdf[Attestato di frequenza., window=_blank]
  * "*Corso di Formazione Generale per i Lavoratori*" (luglio 2021) - cod. att. (link:https://opnitalialavoro.it/verifica-dellautenticita/[137413_5/15, title="Verifica autenticità", window=_blank]). link:/certifications/Sicurezza_sul_Lavoro_P21WT036.pdf[Attestato di superamento., window=_blank]
  * Esperienza di studio all'estero *Estate INPSieme 2017* in Greenwich, Londra, della durata di quattro settimane compresa di corso intensivo di lingua inglese (11/07/2017 - 08/08/2017). link:/certifications/Estate_INPSieme_2017.jpg[Attestato di partecipazione., window=_blank]

=== Certificazioni
  * Certificazione *_Cambridge English First_, Level B2* (luglio 2016) - cert. num. 0053909676. +
  Esame di verifica conseguito in data 22/07/2016 e superato con voto finale di *174 - Grade B*.

== Capacità e competenze tecniche
=== Da ingegnere e progettista meccanico
  * *Conoscenze accademiche di #ingegneria meccanica#*, ovvero: fondamenti di fisica, chimica e matematica, conoscenza delle principali tecnologie per la produzione industriale, metodi di progettazione e gestione di impianti industriali, disegno tecnico, progettazione e prototipazione, fondamenti di energetica, elettrica/elettrotecnica, condizionamento dell'aria, fondamenti di programmazione con LabVIEW, Matlab/Simulink, conoscenze di meccanica stutturale e applicata. +
  Ulteriori dettagli nella pagina dedicata al link:/cv/ingegnere#cdl[curriculum come ingegnere meccanico].

  * #Disegno tecnico e CAD#: capacità di lettura dei disegni, conoscenza delle normative ISO riguardanti messa in tavola, linea e quotatura, capacità di utilizzo dei principali strumenti di misura delle lunghezze (metri, calibri, micrometri); esperienza con AutoCAD e NanoCAD per disegno 2D, con Catia V5, Solidworks e FreeCAD per modellazione 3D; conoscenza di base di Ansys.

=== Da informatico  
    * *Sistemi operativi*: utente avanzato di S.O. basati su Linux, Windows (XP – 11), MacOS e Android, dimestichezza con interfacce a riga di comando (CLI) e gestione dei permessi su vari file system.
    * *Sviluppo web*: fondamenti di programmazione front-end (HTML5, CSS3, Typescript), CMS vari (Hugo, Wordpress, Joomla!, Indico…), installazione e manutenzione di siti web self-hosted con Apache HTTP Server.
    * *Manutenzione di rete*: manutenzione di PC da ufficio e server, conoscenza dei modelli di rete e delle configurazioni RAID/RAIDZ principali, dimestichezza con Bareos, Vorta (Borg) e Rsync per backup e versioning, esperienza con Zabbix per monitoraggio risorse di rete, uso dei protocolli SSH, VNC e RDP per accesso remoto alle macchine, virtualizzazione (Proxmox Virtual Environment, Virt-manager, Citrix Xen Server e altri).
    * *Programmazione*: Python 3, LabVIEW, Matlab/Simulink, fondamenti di GNU Octave, C e altri linguaggi, capacità di manipolazione di database SQL, destrezza con Git.
    * *Office*: suite MS Office 365, LibreOffice e Google Docs, dimestichezza con la libreria Python "docx", conoscenza linguaggi di markup LaTeX, Asciidoctor, Markdown, capacità di gestione di repository documentali (Antora, Obsidian...).

=== Altre capacità e competenze
  * #Progettazione e prototipazione meccanica#: fondamenti di macchine a controllo numerico (CNC), conoscenza di base del linguaggio G-code, uso del software CIMCO Edit; conoscenza dei concetti di tolleranza geometrica e dimensionale, di rugosità e della sua influenza sull'attrito tra componenti meccanici in contatto; conoscenza delle proprietà meccaniche dei materiali metallici, delle lavorazioni e dei trattamenti termici e di rifinitura più comuni; nozioni sulla prototipazione rapida e sulla stampa 3D (FDM, SLA).
  * *Elettrotecnica applicata*: capacità di effettuare piccole riparazioni elettriche su prese, interruttori, piccoli elettrodomestici e piccoli motori AC; competenza nell'uso di multimetro e cercafase.
  * *Fondamenti di #primo soccorso#*: conoscenza delle principali manovre salvavita permesse al soccorritore "laico" come da linee guida della *Croce Rossa Italiana* - della quale sono volontario.
  * *Graphic design e photo editing*: dimestichezza con Adobe Photoshop CS6, quindi con GIMP e Krita per il fotoritocco e Inkscape per manipolazione di vettoriali.
  * *Video editing*: dimestichezza con Kdenlive per montaggio video; competenza con OBS per registrazioni e live streaming - anche con scheda di acquisizione e altre periferiche - conoscenza di base di Vegas (ex Sony Vegas).

=== Capacità e competenze organizzative/relazionali (soft skill)
* Buone capacità di coordinamento delle mansioni personali, di adattamento alle esigenze dei colleghi e di comunicazione in ambienti multiculturali;
* Capacità di gestire situazioni complesse e interazioni impegnative con calma e pazienza, mantenendo sempre un atteggiamento professionale e rispettoso;
* Capacità di problem solving anche sotto pressione;
* Buona velocità di apprendimento;
* Tendenza a socializzare con i colleghi.

== Download
link:/curriculum/comune.pdf[Scarica la versione PDF.^]

=== Allegati
* link:/certifications/FCE_cambridge_first_B1.pdf[All. 1 - Certificato FCE liv. B2^]
* link:/certifications/Attestato_Digital_Manufacturing_Wintime_P21WT036.pdf[All. 2 - Attestato corso di formazione generale per i lavoratori (OPN Italia)^]
* link:/certifications/Sicurezza_sul_Lavoro_P21WT036.pdf[All. 3 - Attestato corso "DIGITAL MANUFACTURING" (EDESIA/WINTIME)^]

link:/curriculum/comune_allegati.pdf[Scarica CV e allegati (PDF unico).^] +
link:/certifications/allegati_cv.pdf[Scarica solo gli allegati.^]

// [cols=3]
// |===
// |Precisione:
// |
// |★★★★★
//
// |Problem solving:
// |
// |★★★★★
//
// |Pazienza:
// |
// |★★★★☆
//
// |Pianificazione:
// |
// |★★★★☆
//
// |Rapporti interpersonali:
// |
// |★★★★☆
//
// |Lavoro di squadra:
// |
// |★★★★☆
//
// |Saper ascoltare:
// |
// |★★★☆☆
//
// |Autonomia:
// |
// |★★☆☆☆
// |===
