---
title: "Curricoli"
date: 2025-02-27
createdDate: 2023-06-12T12:00:00+02:00
language: it
url: "/cv/"
---

Su questo portale sono disponibili quattro versioni del mio curriculum: uno comune che riassume tutte le competenze tecniche e skill lavorative di Emanuele D'Amico, uno specifico da ingegnere meccanico, uno specifico da informatico e uno in formato link:https://europass.europa.eu/it[Europass^].

La versione in formato PDF di ciascun curriculum differisce dalla versione web per brevità, layout e contenuto. Rispetto alle versioni web i PDF sono privi di informazioni superflue (e.g. oggetti di tesi, conoscenze acquisite da ciascun ruolo). Il curriculum Europass è presente perché _purtroppo_ moltissime aziende ancora lo richiedono.

== Curriculum comune
link:/cv/comune/[Visualizza sul web] oppure link:/curriculum/comune.pdf[scarica in PDF^].

== Curriculum come ing. meccanico
link:/cv/ingegnere/[Visualizza sul web] oppure link:/curriculum/MEC.pdf[scarica in PDF^].

== Curriculum come informatico
link:/cv/informatico/[Visualizza sul web] oppure link:/curriculum/SYS.pdf[scarica in PDF^].

== Formato Europass
link:/curriculum/EP-SYS.pdf[Scarica in PDF^].