---
title: 'Curriculum come Informatico'
date: 2025-03-15
createdDate: 2025-03-15T17:46:11+01:00
url: '/cv/informatico'
layout: single # cv_comune
language: it
ShowToc: true
---

== Esperienze lavorative

[#cnr-spin]
=== Sistemista informatico e programmatore per l'Istituto CNR-SPIN sede di Napoli (01/07/2024 - 30/06/2025, _in corso_)
* In qualità di sistemista informatico mi sono occupato di assistenza tecnica al personale di ricerca e di amministrazione durante il passaggio alla nuova rete LAN, risolvendo problemi di connettività e riconfigurazione degli apparati.
* Oltre a questo mi sono occupato della gestione delle macchine operative in sede, tra cui un ipervisore Proxmox a tre nodi con server Nextcloud, eLabFTW, Rustdesk, e un NAS per il backup automatico.
* In qualità di programmatore ho sviluppato l'interfaccia link:https://github.com/PioApocalypse/AMORE/[AMORE^], una GUI open-source per l'inserimento rapido di campioni sull'eLN della sede di Napoli (link:https://elabftw.fisica.unina.it/[eLabFTW^]); ho anche realizzato alcuni piccoli siti web statici.
* Tecnologie utilizzate:
  ** Sistemi operativi *Linux* da Linux Mint 22 ad Almalinux 9;
  ** Strumenti di gestione remota di sistemi di calcolo, in particolare *ssh*;
  ** CMS *Hugo* per la creazione di piccoli siti web;
  ** *Proxmox Virtual Environment* come OS sui nodi del virtualizzatore;
  ** *Python 3* per data parsing/management e sviluppo back-end.
  ** Varie in ordine sparso: git, Docker Compose, Apache HTTP Server, nginx.

[#icranet]
=== Sistemista informatico presso ICRANet Pescara per conto di Soabit s.r.l. (09/01/2023 - 30/06/2023).
* In qualità di sistemista informatico mi sono occupato di gestire e fare manutenzione dell'infrastruttura informatica di ICRANet Pescara, centro di ricerca internazionale di astrofisica relativistica.
* Tale infrastruttura comprendeva macchine fisiche e virtuali, PC, server e workstation, siti web e contenuti online (YouTube, Indico), stampanti, archivi audio video e l'intero sistema dell'infrastruttura LAN (comprendente cavi, switch etc.).
* Altro elemento chiave del lavoro era fornire assistenza al personale interno o esterno a ICRANet, tra cui i membri della faculty, segreteria, amministrazione e ospiti.
* Tecnologie utilizzate:
  ** Sistemi operativi *Linux*, in particolare CentOS 7 (server);
  ** Strumenti di gestione remota di sistemi di calcolo, in particolare *Remmina* per desktop remoto (GUI) e *ssh* per accesso remoto alle shell più macchine Linux (webserver, mail-gw etc.) e Windows (via putty);
  ** Monitorning delle risorse in rete via *Zabbix*;
  ** Backup con *Bareos*, *Rsync*;
  ** *Google Workspace* per amministrazione delle collaborazioni tra utenti interni ed esterni alla sede di Pescara;
  ** CMS *Joomla!* (molto outdated) per sito web, in combinazione con plain-HTML e CSS;
  ** Varie in ordine sparso: git, CMS Hugo/Antora, Asciidoctor e Markdown, Apache HTTP Server, certbot.
* Soft skill maturate:
  ** Efficienza nella manutenzione ordinaria e straordinaria dei PC da ufficio del personale (sia hardware sia software);
  ** Problem solving sotto pressione, pazienza nel gestire e spiegare situazioni con persone poco competenti in informatica.

[#iasait]
=== Webmaster dell'A.S.D. IASA Italia (2018 - 2021).
* Dopo la maturità mi sono occupato nel tempo libero di aggiornare occasionalmente il (vecchio) sito web dell'associazione sportiva dilettantistica IASA Italia - di cui sono stato anche membro in tale occasione.
* La maggior parte delle modifiche erano fatte tramite la console admin di Wordpress, e richiedevano solo una conoscenza di base di HTML oltre ovviamente a una certa dimestichezza con il CMS Wordpress.
* Nel corso di tale esperienza ho acquisito una conoscenza base del CMS Wordpress e della gestione dei contenuti sullo stesso.
* link:https://web.archive.org/web/20240513011758/https://iasa-italia.org/[Snapshot del sito (ora offline) su Internet Archive, window=_blank].

== Istruzione
[#mdmc]
=== Master in Data Management and Curation presso la Scuola Internazionale Superiore di Studi Avanzati (SISSA), Trieste (14/09/2024 - 31/05/2025, in corso).
* Tesi conclusiva: _da concordare con il relatore_.
* Conoscenze acquisite dal corso:
  ** *Fondamenti di sistemi operativi Unix e architetture di rete*.
  ** *Open-science*.
  ** *Programmazione Python*.
  ** *Virtualizzazione e container*.
  ** *Introduzione al machine learning*.

[#ingmec]
=== Laurea Triennale in Ingegneria Meccanica presso l'Università degli Studi di Salerno (2017 - 2024)
* Voto finale: 97/110.
* Tesi di laurea: "Simulazione di un generatore eolico off-grid"
* Conoscenze acquisite dal CdL (in estrema sintesi): fondamenti di fisica, chimica e matematica, conoscenza delle principali tecnologie per la produzione industriale, metodi di progettazione e gestione di impianti industriali, disegno tecnico, progettazione e prototipazione, fondamenti di energetica, elettrica/elettrotecnica, condizionamento dell'aria, fondamenti di programmazione con LabVIEW, Matlab/Simulink, conoscenze di meccanica stutturale e applicata.

=== Corsi di formazione (attestati)
* "*Corso di Formazione Generale per i Lavoratori*" (06/07/2021) - cod. att. (link:https://opnitalialavoro.it/verifica-dellautenticita/[137413_5/15, title="Verifica autenticità", window=_blank]).
  ** Corso di formazione generale dalla durata di 4 ore (tenutosi in videoconferenza) incentrato sui concetti di rischio e prevenzione, e sulla sicurezza sul posto di lavoro.
  ** Organizzato da EDESIA s.r.l. in collaborazione con OPN Italia Lavoro e la CNL.

== Progetti minori
=== Assemblaggio, setup e manutenzione di un piccolo server domestico
La macchina monta Proxmox VE come OS ed è impiegata per automazione delle routine di backup interno, per il self-hosting di servizi open source anche esposti alla rete (Homebox, Nextcloud...) e per la creazione di una piccola VM Windows con GPU passthrough per compatibilità con software esclusivo.

=== Realizzazione di un sito web per il progetto link:https://foxes.spin.cnr.it/[FOXES^] del CNR-SPIN (dicembre 2024)
Il sito è stato realizzato in poco tempo fuori dall'orario di lavoro per un progetto differente dal PNRR a cui ero associato. È stata riutilizzata la versione modificata del medesimo tema (hugo-Hero-Theme) utilizzato per il prototipo del nuovo sito ICRANet (scartato).

=== Realizzazione e mantenimento di questo link:/[sito personale] (giugno 2023 - in corso)
Il sito sul quale vi trovate adesso è un progetto che ha il duplice scopo di servire come _playground_ per migliorare le mie competenze con Hugo, HTML/CSS, Asciidoctor e altro, oltre che fungere da "web-CV" - ossia da sito web contenente in HTML i miei curriculum vitae. È sviluppato a partire dal tema PaperMod per Hugo e mantenuto nel tempo libero. +
Il webserver è una macchina virtuale Oracle Cloud Free Tier x86, con Almalinux 9 e Apache HTTP Server.

=== Realizzazione prototipo di un nuovo sito per link:https://it.wikipedia.org/wiki/ICRANet[ICRANet^] con CMS Hugo (maggio 2023 - _cancellato_)
Dopo aver attentamente analizzato il sito web dell'organizzazione https://www.icranet.org[icranet.org, window=_blank], su richiesta dei docenti della faculty ho lavorato a un prototipo per un nuovo sito statico con Hugo basato sul tema Hero. Il sito doveva presentare i seguenti vantaggi principali rispetto al precedente: design responsivo; minor tempo di caricamento; estensibilità della possibilità di aggiornare il sito al personale con scarse o nulle conoscenze di web-design. Il progetto non è stato portato a termine a causa della scadenza del mio contratto con ICRANet.

// NOTA: VALUTARE BENE RILEVANZA DEI PROGETTI INDIVIDUALI, SE NECESSARIO PORLI PRIMA DELLA SEZIONE ISTRUZIONE

== Capacità e competenze tecniche

[#hardskill]
=== Hard skill
#Sistemi operativi#

* Utente avanzato di S.O. basati su Linux, Windows (XP – 11); esperienza con MacOS e Android.
* Capacità di recupero dati e ripristino di un sistema operativo (disaster recovery).
* Esperienza con interfacce a riga di comando (CLI): Bash, cmd.exe, PowerShell, Cygwin.
* Esperienza di gestione dei permessi su vari file system.

#Sviluppo web#

* Fondamenti di programmazione web front-end: HTML5, CSS3, Typescript.
* CMS/framework vari: Hugo, Wordpress, Joomla!, Indico, Django, Flask.
* Installazione e manutenzione di siti web self-hosted con Apache HTTP Server.

#Manutenzione di rete#

* Manutenzione di PC da ufficio e server.
* Conoscenza dei modelli di rete e delle configurazioni RAID/RAIDZ principali.
* Bareos/bconsole, Vorta (Borg) e Rsync per backup e versioning.
* Esperienza con Zabbix per monitoraggio risorse di rete.
* Uso dei protocolli SSH, VNC e RDP per accesso remoto alle macchine
* Virtualizzazione (Proxmox, Virt-manager, XenServer), containerizzazione (Docker) e automazione (Ansible).
* Familiarità con Windows Server 2003.

#Programmazione#

* Python, LabVIEW, Matlab/Simulink, Bash.
* Fondamenti di GNU Octave, C e altri linguaggi, gestione database SQL.
* Esperienza con git.

#Office#

* Competenza nelle suite da ufficio più diffuse: MS Office 365, LibreOffice, Google Docs.
* Automazione con libreria Python "docx".
* Linguaggi di markup LaTeX, Asciidoctor, Markdown, reStructuredText.
* Esperienza di gestione di repository documentali (Hugo, Antora, Obsidian).

=== Altre capacità e competenze
* *Progettazione e prototipazione meccanica*: fondamenti di macchine a controllo numerico (CNC), conoscenza di base del linguaggio G-code, uso del software CIMCO Edit; conoscenza dei concetti di tolleranza geometrica e dimensionale, di rugosità e della sua influenza sull'attrito tra componenti meccanici in contatto; conoscenza delle proprietà meccaniche dei materiali metallici, delle lavorazioni e dei trattamenti termici e di rifinitura più comuni; nozioni sulla prototipazione rapida e sulla stampa 3D (FDM, SLA).
* *Fondamenti di primo soccorso*: conoscenza delle principali manovre salvavita permesse al soccorritore "laico" come da linee guida della *Croce Rossa Italiana* - della quale sono volontario.
* *Graphic design e photo editing*: dimestichezza con Adobe Photoshop CS6, quindi con GIMP e Krita per il fotoritocco e Inkscape per manipolazione di vettoriali.
* *Video editing*: dimestichezza con Kdenlive per montaggio video; competenza con OBS per registrazioni e live streaming - anche con scheda di acquisizione e altre periferiche - conoscenza di base di Vegas (ex Sony Vegas).
* *Esperienza come <sistemista informatico/programmatore>*: competenze estese in informatica, vedere link:/cv/<curriculum>[curriculum dedicato].

=== Capacità e competenze organizzative/relazionali (soft skill)
* Buone capacità di coordinamento delle mansioni personali, di adattamento alle esigenze dei colleghi e di comunicazione in ambienti multiculturali.
* Capacità di gestire situazioni complesse e interazioni impegnative con calma e pazienza, mantenendo sempre un atteggiamento professionale e rispettoso.
* Capacità di problem solving anche sotto pressione.
* Buona velocità di apprendimento.
* Tendenza a socializzare con i colleghi.

== Download
link:/curriculum/SYS.pdf[Scarica la versione PDF.^]

=== Allegati
* link:/certifications/FCE_cambridge_first_B1.pdf[All. 1 - Certificato FCE liv. B2^]
* link:/certifications/Attestato_Digital_Manufacturing_Wintime_P21WT036.pdf[All. 2 - Attestato corso di formazione generale per i lavoratori (OPN Italia)^]
* link:/certifications/Sicurezza_sul_Lavoro_P21WT036.pdf[All. 3 - Attestato corso "DIGITAL MANUFACTURING" (EDESIA/WINTIME)^]

== Altri contenuti
* link:/cv/comune[Curriculum generale]
* link:/cv/ingegnere[Curriculum come Ing. Meccanico]